default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: ticketfy
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ticketfy_development

test:
  <<: *default
  database: ticketfy_test
